version: '3.9'

services:
 chat-app:
  container_name: tes-simpul
  build:
   context: .
   dockerfile: Dockerfile
  image: railschat
  ports:
   - "3000:3000"

networks:
 default:
  name: global
  external: true